blank_issues_enabled: false
contact_links:
  - name: Construction Progress Dashboard Discussions & Questions
    url: https://github.com/ganesh-dahiphale/construction_project_dashboard/discussions
    about: Ask questions or discuss architectural decisions with the team.
